export const data = [
  { email: 'brenda@exemplo.com',
    password: 'taltaltal',
    name: 'Brenda',
    role: 'mentored',
    careerUsers: [
      { id: 1,
        careerId: 1,
        userId: 1 },
    ],
    userDatum: {
      id: 2,
      userId: 1,
      description: 'Mae de pet',
      level: 'Júnior',
      linkedin: 'meu linkedin',
      topics: 'Front-end',
      photo: 'https://www.petlove.com.br/images/breeds/193530/profile/original/chow_chow-p.jpg?1532538839',
      website: 'meu github',
      inviteCode: 'codigo',
      contactEmail: 'brenda@exemplo.com',
    },
  },
  { email: 'kiara@exemplo.com',
    password: 'taltaltal',
    name: 'Kiara',
    role: 'mentor',
    careerUsers: [
      { id: 1,
        careerId: 2,
        userId: 2 },
    ],
    userDatum: {
      id: 3,
      userId: 2,
      description: 'bebê',
      level: 'Júnior',
      linkedin: 'linkedin kiara',
      topics: 'Produto',
      photo: 'https://www.petlove.com.br/images/breeds/193530/profile/original/chow_chow-p.jpg?1532538839',
      website: '',
      inviteCode: 'codigo',
      contactEmail: 'kiara@exemplo.com',
    },
  },
  { email: 'kiara@exemplo.com',
    password: 'taltaltal',
    name: 'Kiara',
    role: 'mentor',
    careerUsers: [
      { id: 1,
        careerId: 2,
        userId: 2 },
    ],
    userDatum: {
      id: 3,
      userId: 2,
      description: 'bebê',
      level: 'Júnior',
      linkedin: 'linkedin kiara',
      topics: 'Produto',
      photo: 'https://www.petlove.com.br/images/breeds/193530/profile/original/chow_chow-p.jpg?1532538839',
      website: '',
      inviteCode: 'codigo',
      contactEmail: 'kiara@exemplo.com',
    },
  },
];
